services:
  app:
    container_name: crud-app
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure
  db:
    container_name: crud-app-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crud_app
